/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellSongsRouteImport } from './routes/_shell.songs'
import { Route as ShellSearchRouteImport } from './routes/_shell.search'
import { Route as ShellLibraryRouteImport } from './routes/_shell.library'
import { Route as ShellInfrastructureRouteImport } from './routes/_shell.infrastructure'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellAdminRouteImport } from './routes/_shell.admin'
import { Route as ShellPlaylistIdRouteImport } from './routes/_shell.playlist.$id'
import { Route as ShellArtistIdRouteImport } from './routes/_shell.artist.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSongsRoute = ShellSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSearchRoute = ShellSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLibraryRoute = ShellLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInfrastructureRoute = ShellInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminRoute = ShellAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlaylistIdRoute = ShellPlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellArtistIdRoute = ShellArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof ShellAdminRoute
  '/dashboard': typeof ShellDashboardRoute
  '/infrastructure': typeof ShellInfrastructureRoute
  '/library': typeof ShellLibraryRoute
  '/search': typeof ShellSearchRoute
  '/songs': typeof ShellSongsRoute
  '/artist/$id': typeof ShellArtistIdRoute
  '/playlist/$id': typeof ShellPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof ShellAdminRoute
  '/dashboard': typeof ShellDashboardRoute
  '/infrastructure': typeof ShellInfrastructureRoute
  '/library': typeof ShellLibraryRoute
  '/search': typeof ShellSearchRoute
  '/songs': typeof ShellSongsRoute
  '/artist/$id': typeof ShellArtistIdRoute
  '/playlist/$id': typeof ShellPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_shell/admin': typeof ShellAdminRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/infrastructure': typeof ShellInfrastructureRoute
  '/_shell/library': typeof ShellLibraryRoute
  '/_shell/search': typeof ShellSearchRoute
  '/_shell/songs': typeof ShellSongsRoute
  '/_shell/artist/$id': typeof ShellArtistIdRoute
  '/_shell/playlist/$id': typeof ShellPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/dashboard'
    | '/infrastructure'
    | '/library'
    | '/search'
    | '/songs'
    | '/artist/$id'
    | '/playlist/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/dashboard'
    | '/infrastructure'
    | '/library'
    | '/search'
    | '/songs'
    | '/artist/$id'
    | '/playlist/$id'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/register'
    | '/_shell/admin'
    | '/_shell/dashboard'
    | '/_shell/infrastructure'
    | '/_shell/library'
    | '/_shell/search'
    | '/_shell/songs'
    | '/_shell/artist/$id'
    | '/_shell/playlist/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/songs': {
      id: '/_shell/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof ShellSongsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/search': {
      id: '/_shell/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ShellSearchRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/library': {
      id: '/_shell/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ShellLibraryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/infrastructure': {
      id: '/_shell/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof ShellInfrastructureRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin': {
      id: '/_shell/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ShellAdminRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/playlist/$id': {
      id: '/_shell/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof ShellPlaylistIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/artist/$id': {
      id: '/_shell/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ShellArtistIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAdminRoute: typeof ShellAdminRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellInfrastructureRoute: typeof ShellInfrastructureRoute
  ShellLibraryRoute: typeof ShellLibraryRoute
  ShellSearchRoute: typeof ShellSearchRoute
  ShellSongsRoute: typeof ShellSongsRoute
  ShellArtistIdRoute: typeof ShellArtistIdRoute
  ShellPlaylistIdRoute: typeof ShellPlaylistIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAdminRoute: ShellAdminRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellInfrastructureRoute: ShellInfrastructureRoute,
  ShellLibraryRoute: ShellLibraryRoute,
  ShellSearchRoute: ShellSearchRoute,
  ShellSongsRoute: ShellSongsRoute,
  ShellArtistIdRoute: ShellArtistIdRoute,
  ShellPlaylistIdRoute: ShellPlaylistIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
